baseURL: "https://wbknez.github.io/" 
title: Will Knez
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1

params:
    description: "I am a Master's graduate looking to find my place in the scientific world."
    author: Will Knez
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Will Knez
          subtitle: "I am a Master's of Computer Science graduate from Arizona State University looking to find my place in the scientific world.  My primary research interests are agent-based modeling, computational + mathematical sociology, and data visualization.  Pet topics include planetary geology, quantum computational theory, and computer graphics.  I am skilled in Python, C++, and Kotlin, and enjoy exploring the use of technologies such as Jupyter and Dash to make research more accessible to a wider audience."
          imageUrl: "profile.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Will Knez
          buttons:
            - name: Work I Do
              url: projects/
            - name: Books I Read
              url: books
            - name: People I Support
              url: people
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:wknez@asu.edu
        - name: GitHub
          url: https://github.com/wbknez

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Will Knez"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
